In [14]:
from keras.datasets import mnist

(train_images, train_lables), (test_images, test_lables) = mnist.load_data()

In [15]:
train_images.shape

(60000, 28, 28)

In [16]:
len(train_lables)

60000

In [18]:
train_lables

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [19]:
from keras import models
from keras import layers

# ニュートラルネットワークの構成
nw = models.Sequential()
nw.add(layers.Dense(512, activation='relu', input_shape=(28*28,)))
nw.add(layers.Dense(10, activation='softmax'))

In [20]:
# 損失関数
# オプティマイザ
# 訓練とテストを監視する指標
# ..を用意する
nw.compile(optimizer='rmsprop',
                  loss='categorical_crossentropy',
                   metrics=['accuracy'])

In [21]:
train_images = train_images.reshape((60000, 28*28))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28*28))
test_images = test_images.astype('float32') / 255


In [22]:
from keras.utils import to_categorical

train_lables = to_categorical(train_lables)
test_lables = to_categorical(test_lables)

In [23]:
nw.fit(train_images, train_lables, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 2s 4ms/step - loss: 0.2556 - accuracy: 0.9262
Epoch 2/5
469/469 [==============================] - 2s 4ms/step - loss: 0.1039 - accuracy: 0.9692
Epoch 3/5
469/469 [==============================] - 2s 4ms/step - loss: 0.0683 - accuracy: 0.9791
Epoch 4/5
469/469 [==============================] - 2s 4ms/step - loss: 0.0494 - accuracy: 0.9851
Epoch 5/5
469/469 [==============================] - 2s 4ms/step - loss: 0.0377 - accuracy: 0.9886


In [24]:
test_loss, test_acc = nw.evaluate(test_images, test_lables)
print('test_acc:', test_acc)

313/313 [==============================] - 0s 897us/step - loss: 0.0751 - accuracy: 0.9769
test_acc: 0.9768999814987183


In [8]:
import numpy as np
x = np.array([12, 13])
x

array([12, 13])

In [9]:
x.ndim

1

In [12]:
import numpy as np
x = np.array([[5,78,2,34,0],[6,79,3,35,1],[7,80,4,36,2]])
x

array([[ 5, 78,  2, 34,  0],
       [ 6, 79,  3, 35,  1],
       [ 7, 80,  4, 36,  2]])

In [14]:
x.ndim

2

In [15]:
x.ndom

AttributeError: 'numpy.ndarray' object has no attribute 'ndom'

In [16]:
x.ndim

2